// export * from './calcDistance';
export * from './dateDB';
export * from './fetchAPI';
export * from './find_id';
// export * from './handleBrokenImage';
// export * from './numberNaN';
// export * from './next_id';
// export * from './isDeepEqual';
// export * from './window-exists';
// export * from './sumObjectsByKey';
// export * from './barCode';
// export * from './fetchAndSetAll';
// export * from './getApptFromDbSched';
// export * from './buildSchedule';
// export * from './buildSlots';
// export * from './buildFollowups';
export * from './buildAppts';
// export * from './buildDBEntry';
// export * from './findFirstSlot';
// export * from './moveAppt';
// export * from './nullOrUndefined';
// export * from './removeQtyZero';
// export * from './buildTheMonth';
// export * from './fileHandler';